version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: logstash
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash/config/pipelines.yml
        target: /usr/share/logstash/config/pipelines.yml 
        read_only: true
      - type: bind
        source: ./logstash/etc/java-libs/mariadb-java-client-2.4.2.jar
        target: /opt/logstash/logstash-core/lib/jars/mariadb-java-client-2.4.2.jar
      - type: bind
        source: ./logstash/etc/java-libs/postgresql-42.2.7.jre7.jar
        target: /opt/logstash/logstash-core/lib/jars/postgresql-42.2.7.jre7.jar

    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx4g -Xms4g"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.3.1
    container_name: metricbeat
    volumes:
      - type: bind
        source: ./metricbeat/config/metricbeat.yml
        target:  /usr/share/metricbeat/metricbeat.yml
      - type: bind
        source: ./metricbeat/config/metricbeat.reference.yml
        target:  /usr/share/metricbeat/metricbeat.reference.yml
    networks:
      - elk
    depends_on:
      - elasticsearch

  mysql:
    image: mariadb:10.1.19
    container_name: mariadb
    ports:
      - "8083:3306"
    networks:
      - elk
    volumes:
      - ./mysql:/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test

  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5434:5432"
    networks:
      - elk
    volumes:
      - ./postgresql:/postgresql
    environment:
      POSTGRES_PASSWORD: test
    

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
